### PR TITLE
Brighter warning messge

### PR DESCRIPTION
**Pull request by Roilan**
I'm a huge fan of bright error and warning messages since they should be loud. I added `colors` and made warning messages yellow, so they're harder to potentially miss.  Looks like Webstorm decided to tidy up the dev deps as well.

### CODE REVIEW

**Comment by chromakode** [comment]
Hmm. I'm not sure this is a good idea. I agree that loud warnings are in general a good idea, but we should probably keep the warnings vanilla so that they match the ones produced by React. This would only apply to the extra messages like `"text-overflow: ellipsis; does not work in Firefox"`, right?

**Comment by Roilan** [comment]
Ah, you're right. I didn't think about the browsers, I was thinking about node. In that case, I don't think it's a good idea either.

**Comment by chromakode** [comment]
Oh good point, I didn't consider browsers either! Not sure if there'd ever be a case where someone would include this library on the client side, though I suppose it's possible.

**Comment by Roilan** [comment]
That's true but not something we can predict or it adds the possibility of a limitation. Either way, we should stick to matching React's error messages.

**Pull request closed without merging**
