### PR TITLE
Extra props on the Email component

### PR DESCRIPTION
**Pull request by laurent-skim-it**
Purpose:
Providing a little more flexibility to how the email is set up.
Personally, I felt restricted as not being able to set the width of the Email as a property and to be imposed the 600px value (though if I acknowledge this is being best practice and I also know I can still override it using the style property).
More importantly, I need to have an email that is not constrained to the top, aka, I would like to have it 'floating' in the center AND middle. At the moment, the behaviour is center and top (hardcoded value on the Item component that wrap the Email body).

Commit: 
modified the Email component so it now accepts 3 more props: 'width', 'align' and 'align', for which the default are the same as the current behaviour (backward compatibility)

Anyway, unrelated to this PR, but I just wanted to say nice work in general, thanks for saving me some time ;-)

### CODE REVIEW

**Comment by Roilan** [comment]
Hey,

This is great. It looks like Travis isn't happy though.

**Comment by chromakode** [comment]
Hi @laurent-skim-it, thanks for your PR! I agree that adding these props is a good idea. Would you please resolve the [lint errors](https://travis-ci.org/chromakode/react-html-email/jobs/144463295#L819) in the Travis build? Happy to merge up and release once the lint passes.

**Comment by laurent-skim-it** [comment]
Alright, sorry about the delay.
I never used Travis before, and I could not see the errors from the build, so thanks for posting them to me.
I just amended the Email.js file accordingly.
Let me know if you need something else.
Cheers,

**Comment by chromakode** [comment]
Merged in https://github.com/chromakode/react-html-email/commit/75491e7113dd9bb85ab3145daaf57165eba8c964 (I squashed the commits and shortened the commit msg) and released on npm as v1.1.1 :tada: 

Thanks for your contribution Laurent! Glad to hear this library has been useful for you.

**Pull request closed without merging**
