### PR TITLE
adds alt prop to image

### PR DESCRIPTION
**Pull request by Roilan**
As the title says, adds the `alt` prop to image tags. It's pretty important since not all email clients render an image and simply show a block. Updated the test as well and was passing on my end.

### CODE REVIEW

**Comment by chromakode** [comment]
Good call, thank you! Looking into the Travis failure.

**Comment by Roilan** [comment]
:+1: Looks like it's installing 0.15 when it wants 0.14.

**Comment by chromakode** [comment]
Yes, looks like I misinterpreted the effect of peer dependencies on an `npm install`. Fixing!

**Comment by chromakode** [comment]
Merged and passing. Thanks @Roilan! :+1:

**Comment by Roilan** [comment]
Awesome. :+1:

**Pull request merged**
