### PR TITLE
allow string props for image width/height

### PR DESCRIPTION
**Pull request by Roilan**
Allows Image height / width a string prop because `auto` is a common use case to maintain aspect ratio.

### CODE REVIEW

**Comment by chromakode** [comment]
Thanks @Roilan! I've not heard of `width="auto"` in an HTML attribute before. Been looking for an example & checking the specs, but haven't been able to find it. Have you seen this in the wild?

**Comment by Roilan** [comment]
You have a good point. I don't think I've seen people do it outside of using CSS for `width: auto`. The alternative would be to not make height / width a requirement and use the `headCSS` prop.

**Comment by chromakode** [comment]
I think that sounds like the way to go, though there is this caveat to using images without sizes in the markup: https://www.campaignmonitor.com/blog/email-marketing/2007/06/always-include-the-width-and-h/

**Comment by Roilan** [comment]
Hmmm. You have a good point. I'm not entirely sure what the right decision is here. While `auto` as a width or height attribute might not be in spec, it does work and useful in some cases (keeping aspect ratio). Even if we had a default `1px` to meet the above, we wouldn't be able to override it with CSS without `!important` and that's not a good solution either.

**Comment by chromakode** [comment]
It seems like a good idea to include a starting width/height even if the image is going to be scaled, and progressively enhance via CSS if it's supported. Overriding the `width`/`height` via CSS `!important` actually seems like a decent approach for a responsive stylesheet. What do you think?

**Comment by Roilan** [comment]
Out of the options we have mentioned, I think that's the best thing to do. We should also add a note in the documentation mentioning this. Wouldn't want someone spending a great amount of time trying to debug this. I'm good to make the adjustments if you're on board.

**Comment by chromakode** [comment]
That sounds great, thank you!

**Comment by Roilan** [comment]
Closing see #9

**Pull request closed without merging**
