### PR TITLE
Use DOMProperty from react-dom instead of react

### PR DESCRIPTION
**Pull request by ryanscottaudio**
This fixes an issue with the latest version of React (clearly a breaking change that was not marked as such).

### CODE REVIEW

**Comment by Roilan** [comment]
Assuming test pass, LGTM. 👍  

@chromakode take  a look as well

**Comment by ryanscottaudio** [comment]
per https://twitter.com/dan_abramov/status/798926305030877184, it might be good to find another workaround for this

**Comment by chromakode** [comment]
Yikes. We should add a fallback to getting it from `react` for older versions of React, and look for better solutions in the long-term.

I'll look into why the tests are failing.

**Comment by chromakode** [comment]
Testing this + a compat fix at https://github.com/chromakode/react-html-email/compare/fix-react-15-4

**Comment by chromakode** [comment]
@Roilan @ryanscottaudio Merged and released v1.1.3 which fixes this issue. Thanks!

**Comment by mfeuermann** [comment]
thx

**Pull request closed without merging**
